# Generated by Django 5.2.4 on 2025-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Techs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('camera', models.CharField(default='12MP', max_length=8)),
                ('batareya', models.CharField(default='4500mAh', max_length=10)),
                ('harakteri', models.TextField()),
                ('deck', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, default='default/Logitech2.png', null=True, upload_to='books-images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updates_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
