# Generated by Django 5.2.4 on 2025-07-19 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_catagory_alter_techs_options_techs_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catagory',
            table='category',
        ),
        migrations.AlterModelTable(
            name='techs',
            table='techs',
        ),
    ]
